stages:
  data_cleaning:
    cmd: python pipeline/data_cleaning.py
    deps:
      - data/Music Info.csv
      - pipeline/data_cleaning.py
    outs:
      - data/processed/cleaned_data.csv
  content_filtering:
    cmd: python pipeline/content_filtering.py
    deps:
      - data/processed/cleaned_data.csv
      - pipeline/content_filtering.py
    outs:
      - data/processed/transformed_data.npz
      - transformer.joblib

  collabarative_filtering:
    cmd: python pipeline/collabrative_filtering.py
    deps:
      - data/UserHistory.csv
      - data/processed/cleaned_data.csv
      - pipeline/collabrative_filtering.py
    outs:
      - data/processed/collab_filtered_data.csv
      - data/track_ids.npy
      - data/interaction_matrix.npz